# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Raphael Fix
tagline:             ''
description:         'This is my personal website.'
url:                 raphifix.github.io
baseurl:             ''
paginate:            5
paginate_path:       "page:num"
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Raphael Fix
  url:               
  email:             raphifix@gmail.com

# Custom vars
# version:             1.0.0
